using System;
using Il2CppInterop.Runtime;
using Il2CppInterop.Runtime.InteropTypes;

namespace ShreddersNightAurora
{
    /// <summary>
    /// Reads/writes a field by name on the native IL2CPP object. Needed for post-processing parameters: the generic
    /// ParameterOverride&lt;T&gt;.value accessor generated by Il2CppInterop returns garbage in this game (every value
    /// reads 37.0683), so the field address is resolved from the object's real class hierarchy instead.
    /// (No `unmanaged` generic here: that constraint fails to compile against the game's interop mscorlib.)
    /// </summary>
    internal static unsafe class Il2CppParam
    {
        static byte* Field(Il2CppObjectBase obj, string name)
        {
            if (obj == null) return null;
            IntPtr klass = IL2CPP.il2cpp_object_get_class(obj.Pointer);
            while (klass != IntPtr.Zero)
            {
                IntPtr field = IL2CPP.il2cpp_class_get_field_from_name(klass, name);
                if (field != IntPtr.Zero) return (byte*)obj.Pointer + IL2CPP.il2cpp_field_get_offset(field);
                klass = IL2CPP.il2cpp_class_get_parent(klass);
            }
            return null;
        }

        public static bool TryGetFloat(Il2CppObjectBase obj, string name, out float value)
        {
            byte* p = Field(obj, name);
            value = p != null ? *(float*)p : 0f;
            return p != null;
        }

        public static bool TrySetFloat(Il2CppObjectBase obj, string name, float value)
        {
            byte* p = Field(obj, name);
            if (p != null) *(float*)p = value;
            return p != null;
        }

        public static bool TryGetInt(Il2CppObjectBase obj, string name, out int value)
        {
            byte* p = Field(obj, name);
            value = p != null ? *(int*)p : 0;
            return p != null;
        }

        public static bool TryGetBool(Il2CppObjectBase obj, string name, out bool value)
        {
            byte* p = Field(obj, name);
            value = p != null && *p != 0;
            return p != null;
        }

        public static bool TrySetBool(Il2CppObjectBase obj, string name, bool value)
        {
            byte* p = Field(obj, name);
            if (p != null) *p = value ? (byte)1 : (byte)0;
            return p != null;
        }
    }
}
